# Generated by Django 2.2.1 on 2020-03-11 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('makes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=60, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=30)),
                ('doors', models.PositiveIntegerField(default=2)),
                ('lot', models.CharField(help_text='This is the lot number of Vehicle', max_length=20)),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makes.Make')),
            ],
        ),
    ]
